#!/bin/bash

set -e
files=(slim slim-jdk full-jdk)

scala_version=2.12.4
sbt_version=1.0.3

for output in "${files[@]}"; do
    is_alpine=false
    is_jre=false
    install_scala=false

    if [[ $output =~ .*jdk$ ]] ; then
        from=8-jdk
    else
        is_jre=true
        from=8-jre
    fi

    if [[ "$output" =~ ^slim.* ]] ; then
        is_alpine=true
        from=$from-alpine
    fi

    if [[ "$output" =~ ^full.* ]] ; then install_scala=true; fi

    cat <<EOF > $output/Dockerfile
#
# NOTE: This Dockerfile is generated.
#
# Do not edit this file directly.
EOF

    echo "FROM openjdk:$from" >> $output/Dockerfile

    if [ "$install_scala" = true ]; then
        if [ "is_alpine" = true ]; then
            cat <<EOF >> $output/Dockerfile

# Install curl
RUN which curl >> /dev/null 2>&1 || apk add --no-cache curl
EOF
        fi

        install_dir=/usr/share/scala-$scala_version;
        cat <<EOF >> $output/Dockerfile

# Install scala
RUN mkdir -p $install_dir;                                        \\
    curl -fsL https://downloads.typesafe.com/scala/$scala_version/scala-$scala_version.tgz | tar xfz - -C $install_dir && \\
    echo export PATH="$install_dir/bin:\$PATH" >> \$HOME/.bashrc
EOF
    fi

    # Install sbt
    install_dir=/usr/share/
    if [ "$is_alpine" = true ]; then
        cat <<EOF >> $output/Dockerfile

# sbt requires bash and other utils not included
RUN which bash || apk add --no-cache bash bc && \\
    which curl >> /dev/null 2>&1 || apk add --no-cache curl
EOF
    else
        cat <<EOF >> $output/Dockerfile

# sbt requires bc to be installed
RUN apt-get update && apt-get --no-install-recommends install bc
EOF
    fi

    cat <<EOF >> $output/Dockerfile

# Install sbt
RUN mkdir -p $install_dir                                             &&  \\
    curl -L https://github.com/sbt/sbt/releases/download/v$sbt_version/sbt-$sbt_version.tgz | tar xfz - -C $install_dir && \\
    echo export PATH="$install_dir/sbt/bin:\$PATH" >> \$HOME/.bashrc   &&  \\
    $install_dir/sbt/bin/sbt sbtVersion
EOF
done
